### PR TITLE
Transfert repo to gulp-community

### PR DESCRIPTION
**Pull request by A-312**
- [x] Travis ;
 - [x] Coveralls.

### CODE REVIEW

**Comment by phated** [comment]
Try closing and reopening because you pushed before it was enabled.

**Comment by A-312** [comment]
@phated You was right. :D

**Comment by phated** [comment]
The coveralls app doesn't automatically enable a repository.

I've enabled this one https://coveralls.io/github/gulp-community/gulp-terser-js

**Comment by A-312** [comment]
> The coveralls app doesn't automatically enable a repository.
> 
> I've enabled this one https://coveralls.io/github/gulp-community/gulp-terser-js

I didn't have enough right to see that (also error was not explained)^^. That work great, thanks you !

----------

Also, last thing. I don't know if we should enable the `Require status checks to pass before merging` rule for master on this repo 🤔 [Settings > Branches](https://github.com/gulp-community/gulp-terser-js/settings/branch_protection_rules/new)

**Comment by phated** [comment]
I'm not going to enable for the entire organization but I added this branch protection for your project.

Screen Shot 2020-05-08 at 12 58 54 PM

**Comment by A-312** [comment]
We did it :D https://www.npmjs.com/package/gulp-terser-js

(Yeah, I meant juste for me/this repos)

**Pull request merged**
